# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  stl_config = debug
  tests_config = debug
  googletest_config = debug

else ifeq ($(config),release)
  stl_config = release
  tests_config = release
  googletest_config = release

else ifeq ($(config),dist)
  stl_config = dist
  tests_config = dist
  googletest_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := stl tests googletest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

stl:
ifneq (,$(stl_config))
	@echo "==== Building stl ($(stl_config)) ===="
	@${MAKE} --no-print-directory -C stl -f Makefile config=$(stl_config)
endif

tests: stl googletest
ifneq (,$(tests_config))
	@echo "==== Building tests ($(tests_config)) ===="
	@${MAKE} --no-print-directory -C tests -f Makefile config=$(tests_config)
endif

googletest:
ifneq (,$(googletest_config))
	@echo "==== Building googletest ($(googletest_config)) ===="
	@${MAKE} --no-print-directory -C vendor/googletest -f Makefile config=$(googletest_config)
endif

clean:
	@${MAKE} --no-print-directory -C stl -f Makefile clean
	@${MAKE} --no-print-directory -C tests -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/googletest -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   stl"
	@echo "   tests"
	@echo "   googletest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"